import { Catamaran, IBM_Plex_Mono } from 'next/font/google'

import CookieConsent from '@/components/CookieConsent'
import Footer from '@/components/Footer'
import { ScrollToTopButton } from '@/components/ToTopButton'
import Header from '@/components/header/Header'
import './globals.css'

const ibm_plex_mono = IBM_Plex_Mono({
	display: 'block',
	variable: '--font-ibm_plex_mono',
	weight: ['500', '400'],
	subsets: ['latin'],
})

const catamaran = Catamaran({
	display: 'block',
	variable: '--font-catamaran',
	weight: ['500', '400'],
	subsets: ['latin'],
})

export const metadata = {
	title: 'Hundeschule',
	description: 'Generated by create next app',
}

async function getHeader() {
	const res = await fetch(
		`${process.env.PAYLOAD_SERVER_URL}/api/globals/header/`,
		{
			next: { revalidate: 3600 },
		}
	)

	if (!res.ok) {
		throw new Error('Failed to fetch data')
	}

	return res.json()
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const header = await getHeader()
	return (
		<html
			lang="de"
			className={`${ibm_plex_mono.variable} ${catamaran.variable}`}
		>
			<body>
				<Header headerLink={header} />
				{children}
				<ScrollToTopButton />
				<CookieConsent />
				<Footer />
			</body>
		</html>
	)
}
