import { IBM_Plex_Mono, Catamaran, Roboto } from "next/font/google";
import { Locale, i18n } from "../../i18n-config";
import { getDictionary } from "../../get-dictionary";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

import "./globals.css";
import Logo from "./Logo";
import Footer from "./footer/page";
import Navbar from "./Navbar";
import TopBar from "./TopBar";
import { ScrollToTopButton } from "./ToTopButton";

const ibm_plex_mono = IBM_Plex_Mono({
  display: "block",
  variable: "--font-ibm_plex_mono",
  weight: ["500", "400"],
  subsets: ["latin"],
});

const catamaran = Catamaran({
  display: "block",
  variable: "--font-catamaran",
  weight: ["500", "400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Hundeschule",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { lang: Locale };
}) {
  const dictionary = await getDictionary(params.lang);
  return (
    <html
      lang={params.lang}
      className={`${ibm_plex_mono.variable} ${catamaran.variable}`}
    >
      <body>
        <header>
          <TopBar />
          <nav>
            <div>
              <Logo params={params} />
              <Navbar dictionary={dictionary.menu} />
            </div>
          </nav>
          <ScrollToTopButton />
        </header>
        <main>{children}</main>
        <footer>
          <div>
            <Footer />
          </div>
        </footer>
      </body>
    </html>
  );
}
