import { Catamaran, IBM_Plex_Mono } from 'next/font/google'
import { Locale, i18n } from '../../i18n-config'

export async function generateStaticParams() {
	return i18n.locales.map(locale => ({ lang: locale }))
}

import Footer from '@component/components/Footer'
import { ScrollToTopButton } from '@component/components/ToTopButton'
import Header from '@component/components/header/Header'
import { getDictionary } from '@component/get-dictionary'
import './globals.css'

const ibm_plex_mono = IBM_Plex_Mono({
	display: 'block',
	variable: '--font-ibm_plex_mono',
	weight: ['500', '400'],
	subsets: ['latin'],
})

const catamaran = Catamaran({
	display: 'block',
	variable: '--font-catamaran',
	weight: ['500', '400'],
	subsets: ['latin'],
})

export const metadata = {
	title: 'Hundeschule',
	description: 'Generated by create next app',
}

async function getHeader() {
	const res = await fetch(
		`${process.env.PAYLOAD_SERVER_URL}/api/globals/header/`,
		{
			next: { revalidate: 3600 },
		}
	)

	if (!res.ok) {
		throw new Error('Failed to fetch data')
	}

	return res.json()
}

export default async function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode
	params: { lang: Locale }
}) {
	const dictionary = await getDictionary(params.lang)
	const header = await getHeader()
	return (
		<html
			lang={params.lang}
			className={`${ibm_plex_mono.variable} ${catamaran.variable}`}
		>
			<body>
				<Header headerLink={header} dictionary={dictionary} />
				{children}
				<ScrollToTopButton />
				<Footer />
			</body>
		</html>
	)
}
